### ISSUE TITLE
Data  too long for column 'key' at row 。。。。

### ISSUE THREAD

**Issue by yixiuzhemu** [archguard/scanner#1]
1、Download scan_sourcecode-1.4.3-all.jar
2、create database archguard
3、start archguard-1.5.1.jar by use java -jar to create tables
4、use java "-Ddburl=jdbc:mysql://localhost:3306/archguard?user=root&password=&useSSL=false" -jar scan
_sourcecode-1.4.3-all.jar --system-id=6 --language=java --path=.  to scan soucecode

appear exception info at last 
org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.BatchUpdateException: Data truncation: Data
 too long for column 'key' at row 115 [statement:"null", rewritten:"null", parsed:"null", arguments:{positional:{}, name
d:{}, finder:[]}]

**Comment by phodal** [comment]
fixed in https://github.com/archguard/archguard/commit/37150891ebe31676d6b4cee5e3b457c03b354b40
