### ISSUE TITLE
Look me：ArchGuard 部署搭建 —— help ！！！

### ISSUE THREAD

**Issue by xuexiansen123** [archguard/scanner#2]
本人小白一枚，最近刚刚接触`ArchGuard`，在部署搭建过程中遇到一些问题，麻烦大佬们各显神通，救救小菜鸡。
以下操作按照`READ.ME`进行，如有理解不当，还请大家多多指教。
[ArchGuard scanner](https://github.com/archguard/scanner/) - scan source code, binary data and othes, and feed to database.
[ArchGuard frontend](https://github.com/archguard/archguard-frontend) - visualization results & dashboard
[ArchGuard backend](https://github.com/archguard/archguard) - connect scanner and show data.

### scan_git
执行`./gradlew :scan_git:run --args="--path=xxx（自己代码仓地址）"`，出现以下错误
```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/5g_build/5g_Main/scanner/diff_changes/build.gradle.kts' line: 1

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.6.10'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.6.10')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 8s
```
### scan_sourcecode
执行`java "-Ddburl=jdbc:mysql://localhost:3306/archguard?user=root&password=&useSSL=false" -jar scan_sourcecode-1.1.7-all.jar --system-id=8 --path=scan_git --language=kotlin`，出现以下错误
```
ssword=&useSSL=false" -jar scan_sourcecode-1.1.7-all.jar --system-id=8 --path=scan_git --language=kotlin
Error: Unable to access jarfile scan_sourcecode-1.1.7-all.jar
```

**Comment by phodal** [comment]
这个一般是在前后端搭建成功后使用的，clone 后在目标目录下执行
