### ISSUE TITLE
bytecode scaner无法识别@RequestMapping api

### ISSUE THREAD

**Issue by whitekoolz** [archguard/scanner#6]
**bytecode scaner无法识别@RequestMapping api**
![image](https://user-images.githubusercontent.com/18185097/164651309-0b3deb34-bbb3-40c1-b4ad-e54e61d01c0b.png)
由于method的类型是 RequestMethod枚举

![image](https://user-images.githubusercontent.com/18185097/164651440-041aea12-46a6-4e0a-b928-f62caf846394.png)
而扫描的时候是字符串来比对

spring-web 版本 5.0.6.RELEASE

**Comment by phodal** [comment]
来个 PR？

**Comment by teobler** [comment]
@whitekoolz 没空的话我可以来？
